name: Docker Image CI (build and publish)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag dns-deployment:test .
        
    - name: Login to Docker Repository
      run: docker login --username "${{secrets.REPOSITORY_USERNAME}}" --password "${{secrets.REPOSITORY_PASSWORD}}"
      
    - name: Tag with remote repository
      run: docker tag dns-deployment registry.digitalocean.com/part3-project/dns-deployment
      
    - name: Push to remote repository
      run: docker push registry.digitalocean.com/part3-project/dns-deployment
